SELECT
	AVG(TOTAL_WINNINGS)
FROM
(
SELECT 
	NAME
    ,DATE
    ,SUM(PRICE) AS TOTAL_WINNINGS
FROM
	five_ep
WHERE CONCAT(TRIM(NAME),TRIM(DATE)) IN (

SELECT
CONCAT(TRIM(NAME),TRIM(DATE))
    
FROM
	five_ep
WHERE
	WIN = 1.0
AND
	EVENTTYPE = 'Showcase Showdown'
)

AND
	WIN = 1.0
 GROUP BY NAME, DATE
 ) T;
 
 
 -- TABLE RELATIONSHIPS
 /*
	ONE-TO-ONE (1:1) ex: for privacy concerns - 1:1 relatonship is implemented
    ONE-TO-MANY(1:N) [1:N + 1:1 = 1:N] IF RELATION IS 1:N IN ONE DIRECTION AND 1:1 IN THE OTHER DIRECTION THEN THE RELATIONSHIP BETWEEN THE 2 TABLES IS 1:N
    MANY-TO-MANY(M:N) IF RELATION IS 1:N IN ONE DIRECTION AND 1:N IN THE OTHER DIRECTION AS WELL THEN THE RELATIONSHIP BETWEEN THE 2 TABLES IS M:N
*/

-- PRIMARY KEY CANNOT BE NULL

/*
	CONNECTING TABLES (M:N)
    CREATE A LINKING TABLE WITH FK/CPK FROM BOTH TABLES
*/

-- ER DIAGRAM & RELATIONAL SCHEMAS
/* RELATIONAL SCEHMA - MAP OF DATABASE ONCE CREATED
	ER DIAGRAM - THEORITICAL : DURING PLANNING/DESIGNING THE DATABASE
    
    ERDPLUS.COM TO GENERATE
    USE LABELS TO ADD COMMENTS FOR ADDITIONLA INFORMATION ON THE HOMEWORK
*/

SELECT
	*
FROM
	Dogs D
INNER JOIN
	Owners O
ON
	D.ownerid > O.ownerid;
    
    
SELECT
	AVG(TOTAL_WINNINGS)
FROM
(
SELECT 
	NAME
    ,DATE
    ,SUM(PRICE) AS TOTAL_WINNINGS
FROM
	five_ep T1
INNER JOIN
 (

SELECT
NAME, DATE
FROM
	five_ep
WHERE
	WIN = 1.0
AND
	EVENTTYPE = 'Showcase Showdown'
) T2
ON   T1.NAME = T2.NAME
AND	 T1.DATE = T2.DATE
)
WHERE

	WIN = 1.0
 GROUP BY NAME, DATE
;
 
